networks:
  default:
    external:
      name: dev-infras

volumes:
  esdata:

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.2.1
    container_name: elasticsearch
    restart: unless-stopped
    ports:
      - '${ELASTIC_PORT}:9200'
    environment:
      - node.name=es01
      - discovery.type=single-node
      - cluster.name=es-docker-cluster
      - network.host=0.0.0.0
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - xpack.security.enabled=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - esdata:/usr/share/elasticsearch/data
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'curl -sS http://localhost:9200/_cluster/health || exit 1',
        ]
      interval: 30s
      timeout: 10s
      retries: 20
